app.description = "correct-me"
app.port        = 8080

db.host         = "localhost"
db.port         = 5432
db.name         = "mydb"
db.user         = "myuser"
db.pass         = "mypassword"

speller.url     = "https://speller.yandex.net/services/spellservice.json/checkText"
speller.enabled = false
