name:                correct-me-v2
version:             0.1.0.0
github:              "almayor/correct-me-v2"
license:             BSD-3-Clause
author:              "Alexander Mayorov"
maintainer:          "mayorovme@gmail.com"
copyright:           "2024 Alexander Mayorov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/almayor/correct-me-v2#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bcrypt
  - bytestring
  - contravariant-extras
  - deriving-aeson
  - either
  - fast-logger
  - hasql
  - hasql-migration
  - hasql-pool
  - hasql-th
  - hasql-transaction
  - jose
  - lens
  - lens-aeson
  - monad-logger
  - mtl
  - network-uri
  - profunctors
  - servant
  - servant-auth
  - servant-auth-server
  - servant-auth-swagger
  - servant-client
  - servant-server
  - servant-swagger
  - swagger2
  - text
  - time
  - tomland
  - transformers
  - tuple
  - utf8-string
  - vector
  - wai
  - wai-extra
  - wai-logger
  - warp >= 3.2.4
  - wreq

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions: ConstraintKinds
                    , DataKinds
                    , DeriveAnyClass
                    , DeriveGeneric
                    , DerivingStrategies
                    , FlexibleContexts
                    , GeneralizedNewtypeDeriving
                    , InstanceSigs
                    , MultiParamTypeClasses
                    , NamedFieldPuns
                    , OverloadedStrings
                    , RecordWildCards
                    , ScopedTypeVariables
                    , TemplateHaskell
                    , TypeApplications
                    , TypeFamilies
                    , TypeOperators

executables:
  correct-me-v2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - correct-me-v2

tests:
  correct-me-v2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - correct-me-v2
