name: Build, Test and Push Docker Image

on:
  push:
    paths:
    - 'src/**'
    - 'exe/**'
    - 'test/**'
    - 'Dockerfile'
    - '.github/workflows/ci-cd.yml'
    - 'package.yaml'
    - 'stack.yaml'
    - 'docker-compose.yaml'
  workflow_dispatch:

jobs:
  run-tests-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
      
    - name: Build and cache Docker image (no push)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: almayor/correct-me:latest
        #caching intermediate layers
        cache-from: type=registry,ref=almayor/correct-me:cache
        cache-to: type=registry,ref=almayor/correct-me:cache,mode=max
        #don't push before testing but load to `docker image ls`
        push: false
        load: true

    - name: List Docker images in cache
      run: docker image ls

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    
    - name: Run tests inside Docker container
      run: docker-compose --entrypoint stack run -T app test
    
    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: almayor/correct-me:latest
        platforms: linux/amd64
        cache-from: type=registry,ref=almayor/correct-me:cache
        # push to the registry
        push: true
  
  update-api-docs:
    needs: run-tests-and-push-image
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # Get updated API docs
    - name: Write docs
      run: |
        docker run almayor/correct-me --output-docs > docs/api_docs.md

    # Commit and push the updated file back to the repository
    - name: Commit and Push Documentation
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/api_docs.md
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Update API documentation on push"
          git push https://x-access-token:${GH_PAT}@github.com/almayor/correct-me.git HEAD:main
        fi
