name: Build, Test and Push Docker Image

on:
  push:
    paths:
    - 'src/**'
    - 'exe/**'
    - 'test/**'
    - 'Dockerfile'
    - '.github/workflows/docker-publish.yml'
    - 'package.yaml'
    - 'stack.yaml'
    - 'docker-compose.yaml'
  workflow_dispatch:

jobs:
  run-tests-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      
      - name: Build and cache Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: almayor/correct-me:latest
          platforms: linux/amd64,linux/arm64
          #caching intermediate layers
          cache-from: type=registry,ref=almayor/correct-me:cache
          cache-to: type=registry,ref=almayor/correct-me:cache,mode=max
           #don't push before testing
          push: false

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Run tests inside Docker container
        run: |
          docker-compose up -d
          docker-compose exec app stack test
      
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: almayor/correct-me:latest
          cache-from: type=registry,ref=almayor/correct-me:cache
          push: true  # Push the image to the registry
