name: Build, Test and Push Docker Image

on:
    push:
        paths:
            - 'src/**'
            - 'exe/**'
            - 'test/**'
            - 'Dockerfile'
            - '.github/workflows/docker-publish.yml'
            - 'package.yaml'
            - 'stack.yaml'
            - 'docker-compose.yaml'

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to DockerHub
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: Install Docker Compose
          run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        
        - name: Build Docker image
          run: docker-compose build app

        - name: Start Database with Docker Compose
          run: docker-compose up -d postgres
        
        - name: Wait for PostgreSQL to be up
          run: |
            for i in {1..30}; do
              if docker-compose exec db pg_isready -U postgres; then
                echo "PostgreSQL is up!"
                exit 0
              fi
              echo "Waiting for PostgreSQL..."
              sleep 5
            done
            echo "PostgreSQL did not start in time" >&2
            exit 1
          
        - name: Run tests inside Docker container
          run: |
            docker-compose up -d app
            docker-compose exec app stack test

        - name: Push Docker image
          if: success()
          run: docker-compose push app 